### ISSUE TITLE
Negative weight

### ISSUE THREAD

**Issue by bthe** [gadget-framework/gadget3#19]
I guess this is a harmless issue, but the report weight at length is often negative, albeit close to zero, when the modelled abundance for a age-length-stock combination is zero. I guess this is more an observation, as the mean weight at length is a abundance weighted but it produces pretty interesting plots:

![image](https://user-images.githubusercontent.com/7022612/108352709-26f26e80-71df-11eb-92b3-72ee05642034.png)

**Comment by lentinj** [comment]
The mean weight of no fish is a bit of a philosophical question anyway :)

We convert weight to total weight and back again in a lot of actions (pretty much only growth works with mean weight), so that along with avoid_zero_vec() will cause it to fall to nearly-zero rather than stay at the previous level.

Falling negative is a bit worrying, I can't think any obvious reasons for it though.

**Comment by bthe** [comment]
> Falling negative is a bit worrying, I can't think any obvious reasons for it though.

Yes, but this is, as shown in the figures, very close to 0 so I suspect that this is a rounding effect that lingers when the catch is subtracted from the total abundance.

**Comment by lentinj** [comment]
Fair enough. Regardless, if a stock comes back from the dead then we're adding the renewed (or matured) total weight together, so the negative mean isn't going to have an effect.

All of gadget2's ``if (.. < verysmall)`` will stop weight changing when the stock hits ~0, but that's not an option here.
